title: "My 100 Days of Homelab Challange Site"
author: "Rick Ibrahim"
description: "This is where I will blog my experiences participating in the 100 days of Homelab Challange."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: Home,url: "index.html", sidebaricon: home}
  - {file: "archive.html", sidebaricon: archive}
  - {file: "README.md", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Twitter, icon: twitter, url: "https://x.com/CableDog_Rick"}
  - {title: Github, icon: github, url: "https://github.com/richard-ibrahim"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: Challange Homepage, icon: link, url: "https://100daysofhomelab.com/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
